---
- name: Install Check MK and dependencies
  yum: name='{{item}}' state=present validate_certs={{check_mk_agent_validate_certs}}
  with_items:
    - '{{check_mk_agent_rpm}}'
    - xinetd
  notify: Restart xinetd

- name: Configure xinetd
  lineinfile: dest=/etc/xinetd.d/{{check_mk_agent_xinetd_file}} regexp='^(\s*)#?({{item.key}}\s+)=' line='\1\2= {{item.value}}' backrefs=yes
  with_dict:
    disable: 'no'
    only_from: '{{check_mk_agent_servers | join(" ")}}'
  register: check_mk_agent_r__xinetd
  notify: Restart xinetd
  ignore_errors: ansible_check_mode and "does not exist" in check_mk_agent_r__xinetd.msg

- name: Enable and start xinetd service
  service: name=xinetd state=started enabled=yes

- name: Install extra plugins
  get_url: dest=/usr/lib/check_mk_agent/plugins url={{item}} mode=0755 validate_certs={{check_mk_agent_validate_certs}}
  with_items: '{{check_mk_agent_plugins}}'
